### ISSUE TITLE
Questão 1 - a) Escreva uma função que conte o número de consoantes de uma string passada como parâmetro.

### ISSUE THREAD

**Issue by mateus-azevedo** [mateus-azevedo/AV1-PE#1]
a) Escreva uma função que conte o número de consoantes de uma string passada como parâmetro.

**Comment by viniciusoliveiras** [comment]
Iniciado dia 18/09

**Comment by viniciusoliveiras** [comment]
Questão finalizada e esperando revisão dos demais participantes para possível otimização e, posteriormente, envio.

**Comment by mateus-azevedo** [comment]
Realizei alterações na branch atualize sua branch local em relação a remoto
