### ISSUE TITLE
Questão 2 – d) Faça um programa que leia uma matriz de 5 linhas e 5 colunas contendo as seguintes informações sobre alunos de uma disciplina: 1. Coluna: número de matrícula (use um inteiro) 2. Coluna: Avaliação 1 3. Coluna: Avaliação 2 4. Coluna: Média dos trabalhos 5. Coluna: Nota final Elabore um programa que: Leia as quatro primeiras informações de cada aluno Calcule a nota final como sendo a soma da média das avaliações e da média dos trabalhos Imprima a matrícula do aluno que obteve a maior nota final Imprima a média aritmética das notas finais

### ISSUE THREAD

**Issue by mateus-azevedo** [mateus-azevedo/AV1-PE#10]

**Comment by mateus-azevedo** [comment]
## Iniciando o Projeto 

- [x] 1. Coluna: número de matrícula (use um inteiro)
- [x] 2. Coluna: Avaliação 1
- [x] 3. Coluna: Avaliação 2
- [x] 4. Coluna: Média dos trabalhos
- [x] 5. Coluna: Nota final

 Média das avaliações == (avaliação 1 + avaliação 2 ) / 2
 Nota Final == média das avaliações + média dos trabalhos

##### Imprimir a matrícula do aluno que obteve a maior nota final 
##### Imprimir a média aritmética das notas finais

**Comment by mateus-azevedo** [comment]
@Rhuan-Gonzaga Precisamos utilizar a estrutura struct aqui depois dá uma help

**Comment by Rhuan-Gonzaga** [comment]
```
struct dadosaluno {
     int matricula;
    float av1 ,av2 , media , notafinal;
};

main(){
     struct dadosaluno info;

}
```

**Comment by mateus-azevedo** [comment]
Tá voando @Rhuan-Gonzaga estava quebrando cabeça nisso agora
