### ISSUE TITLE
Questão 3 – e) Faça um programa para gerar automaticamente números entre 0 e 99 de uma cartela de bingo. Sabendo que cada cartela deverá conter 5 linhas de 5 números, gere estes dados de modo a não ter números repetidos dentro das cartelas. O programa deve exibir na tela a cartela gerada (exibir como uma cartela real).

### ISSUE THREAD

**Issue by mateus-azevedo** [mateus-azevedo/AV1-PE#16]

**Comment by Rhuan-Gonzaga** [comment]
#include <stdio.h>
#include <stdlib.h>

int main() {
  int numeros[5][5], continua, i, j, c, l;

  srand(time(NULL));

    for (i=0;i<5;i++){     
        for (j=0;j<5;j++){ 
            do{   
                continua=0;
                numeros[i][j]=rand()%99; /* gera numeros aleatorios até 99 */

                for (l=0;l<5;l++){
                    for (c=0;c<5;c++){
                      if (numeros[i][j]==numeros[l][c] && (i!=l && j!=c)){  /* comparando os numeros para ve se são iguais */
                      continua++;
                      }
                    }
                }
                 } while(continua!=0); /* se mantem continuando até terminar o for */
        }
    }
                for (l=0;l<5;l++)
                {
                    for (c=0;c<5;c++)
                    {
                       printf(" \t %d ", numeros[l][c]); /* imprime a cartela de numeros */ 
                    }
                    printf("\n");
                }
    return 0;
}

**Comment by Rhuan-Gonzaga** [comment]
Deem uma olhada no codigo

**Comment by mateus-azevedo** [comment]
> Deem uma olhada no codigo

Rhuan não precisa postar o código aqui kk esqueceu?? a gente consegue ver pela branch. 
A forma ideal que você poderia referenciar aqui... seria assim:

https://github.com/mateus-azevedo/AV1-PE/blob/24ca0fa22d9b466be35ee9c9ca880506cebaf255/Questao2/questao2_d.cpp#L26-L29

Porque já te manda diretamente para o teu código

**Comment by mateus-azevedo** [comment]
@Rhuan-Gonzaga tentei compilar o teu código e me retornou esse erro: 

> questao3E.c:7:9: error: 'time' was not declared in this scope
>     7 |   srand(time(NULL));

https://github.com/mateus-azevedo/AV1-PE/blob/219f878e1fd9f17c6b3047ec4022cfb46aa2df95/questao3E.c#L7

Vamos tirar um dia para entrar na call para dar continuidade a questão
